using System.Collections.Generic;
using System.Linq;
using ManagerServer.Globalization;
using ManagerServer.Model;
using ManagerServer.Helpers;
using ManagerServer.Attributes;
using ManagerServer.Api.Businesses.Business.Reports.ProjectProfitAndLossStatement;

namespace ManagerServer.HttpHandlers.Businesses.Business.Projects
{
    [ProtoContract]
    [Title(nameof(Strings.Project))]
    [Guide("The `Project` report provides a detailed profitability analysis for a specific project by comparing all income earned against expenses incurred.")]
    [Guide("This report helps you understand whether a project is profitable by calculating the net profit, which is the difference between total income and total expenses.")]
    [Guide("Use this report to evaluate project performance, make informed decisions about resource allocation, and assess whether projects are meeting their financial objectives.")]
    [Header("Report Structure")]
    [Guide("The report is organized into two main sections that summarize all financial activity for the project:")]
    [Guide("`Income` - Shows all revenue generated by the project, grouped by income account. This includes sales invoices, receipts, and any other income transactions linked to the project.")]
    [Guide("`Expenses` - Shows all costs directly attributed to the project, grouped by expense account. This includes purchase invoices, payments, and any other expense transactions linked to the project.")]
    [Guide("The final line displays the `Profit` (or loss), which is calculated as total income minus total expenses. A positive value indicates a profitable project, while a negative value indicates a loss.")]
    [Header("Time Period and Data Selection")]
    [Guide("The report automatically determines the time period based on the earliest and latest transaction dates for the project. This ensures all project-related transactions are captured regardless of when they occurred.")]
    [Guide("Only transactions that have been explicitly linked to this project are included in the calculations. Transactions without a project assignment will not appear in this report.")]
    [Guide("The report uses base currency amounts for all calculations, ensuring accurate profit calculations even when dealing with foreign currency transactions.")]
    [LinkGuide("To learn more about creating and managing projects, see:", typeof(ProjectForm))]
    internal sealed class ProjectReportView : DefaultView<GetProjectProfitAndLossStatementView>
    {
    }
}