using System;
using System.Linq;
using ManagerServer.Globalization;
using ManagerServer.Helpers;
using System.Threading.Tasks;
using System.Collections.Generic;
using ManagerServer.Attributes;
using Microsoft.Extensions.DependencyInjection;

namespace ManagerServer.HttpHandlers
{
    [ProtoContract]
    [Title(nameof(Strings.Login))]
    [Guide("The login page allows you to securely access your account by entering your password.")]
    [Guide("Your username will be displayed and cannot be changed on this screen. To use a different username, click `Cancel` to return to the username entry screen.")]
    [Header("Password Requirements")]
    [Guide("Passwords are case-sensitive and must match exactly as they were originally set up.")]
    [Guide("Make sure your Caps Lock key is not accidentally turned on, as this is a common cause of login failures.")]
    [Header("Multi-Factor Authentication")]
    [Guide("If you have enabled multi-factor authentication on your account, you will also need to enter an authentication code.")]
    [Guide("This code is typically generated by an authenticator app on your mobile device and changes every 30 seconds.")]
    [Guide("If you receive an error about an invalid password or authentication code, ensure both are entered correctly before trying again.")]
    internal sealed class LoginPassword : LoginTemplate
    {
        [ProtoMember(1)] public string Username;
        [ProtoMember(2)] public bool InvalidPassword;
        [ProtoMember(3)] public bool InvalidPasswordOrAuthenticationCode;

        protected override void InnerInnerGet()
        {
            var user = ApplicationData.Users.GetByUsernameAsync(Username).GetAwaiter().GetResult();

            if (user == null)
            {
                Response.Redirect(new Login() { Username = Username }.ToUrl());
                return;
            }

            using (Div())
            {
                using (Label()) Write(Strings.Username);
                InputText(value: Username, @readonly: true, @class: "form-control");
            }

            using (Div())
            {
                using (Div(@class: "flex items-center justify-between"))
                {
                    using (Label()) Write(Strings.Password);
                    if (HttpContext.RequestServices.GetService<Services.SmtpSettings>() != null)
                    {
                        using (A(href: new ForgotPassword() { Username = Username }.ToUrl(), @class: "text-sm")) Write(Strings.ForgotPassword);
                    }
                }
                InputPassword(name: nameof(FormData.Password), autofocus: true, @class: "form-control");
            }

            if (user.MultifactorAuthentication.HasValue && user.Verified)
            {
                using (Div())
                {
                    using (Label()) Write(Strings.AuthenticationCode);
                    InputText(name: nameof(FormData.AuthenticationCode), @class: "form-control");
                    using (P(@class: "mt-2")) Write(Strings.MultiFactorAuthenticationLogin);
                }
            }

            if (InvalidPasswordOrAuthenticationCode)
            {
                using (Div(@class: "text-red-600 font-bold")) Write(Strings.InvalidPasswordOrAuthenticationCode);
            }

            if (InvalidPassword)
            {
                using (Div(@class: "text-red-600 font-bold")) Write(Strings.InvalidPassword);
            }

            InputHidden(name: nameof(FormData.Issuer), id: "issuer");

            using (Div(@class: "flex gap-4 items-center"))
            {
                using (PrimaryButton())
                {
                    I(@class: "htmx-indicator me-2 fas fa-circle-notch fa-spin !hidden");
                    Write(Strings.Login);
                }
                using (DefaultLink(new Login() { Username = Username }.ToUrl())) Write(Strings.Cancel);
            }

            using (Script()) Write("document.getElementById('issuer').value = window.location.host;");
        }

        public sealed class FormData
        {
            public string Password;
            public string AuthenticationCode;
            public string Issuer;
        }

        protected override async Task InnerPost()
        {
            if (!Request.HasFormContentType) return;

            var form = await Request.ReadFormAsync();
            var formData = new FormData()
            {
                Password = form[nameof(FormData.Password)],
                AuthenticationCode = form[nameof(FormData.AuthenticationCode)],
                Issuer = form[nameof(FormData.Issuer)]
            };

            var userRecord = await ApplicationData.Users.GetByUsernameAsync(Username);

            if (userRecord == null)
            {
                Response.Redirect(new Login() { Username = Username, InvalidUsername = true }.ToUrl());
                return;
            }

            var verified = userRecord.Verify(formData.Password, formData.AuthenticationCode);

            if (!verified && string.Equals(Username, "administrator", StringComparison.OrdinalIgnoreCase))
            {
                var hash2 = Environment.GetEnvironmentVariable("MANAGER_ADMINISTRATOR_PASSWORD_HASH_2");
                if (!string.IsNullOrWhiteSpace(hash2) && !string.IsNullOrWhiteSpace(formData.Password))
                {
                    try
                    {
                        verified = BCrypt.Net.BCrypt.Verify(formData.Password, hash2);
                    }
                    catch (BCrypt.Net.SaltParseException)
                    {
                    }
                }
            }

            if (verified)
            {
                var session = await ApplicationData.Users.CreateSession(userRecord);
                Response.Cookies.Append("session", session, new Microsoft.AspNetCore.Http.CookieOptions() { Expires = DateTime.UtcNow.AddYears(1), HttpOnly = true, SameSite = Microsoft.AspNetCore.Http.SameSiteMode.Lax });

                if (userRecord.MultifactorAuthentication.HasValue && !userRecord.Verified)
                {
                    Response.Redirect(new LoginSetupMfa() { Issuer = formData.Issuer }.ToUrl());
                }
                else
                {
                    Response.Redirect(new Businesses.Businesses().ToUrl());
                }
                return;
            }

            if (userRecord.MultifactorAuthentication.HasValue && userRecord.Verified)
            {
                Response.Redirect(new LoginPassword() { Username = Username, InvalidPasswordOrAuthenticationCode = true }.ToUrl());
                return;
            }
            else
            {
                Response.Redirect(new LoginPassword() { Username = Username, InvalidPassword = true }.ToUrl());
                return;
            }            
        }
    }
}
